-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Warehouse".products
(
    id integer NOT NULL DEFAULT nextval('"Warehouse"."Product_id_seq"'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    quantity integer DEFAULT 1,
    price double precision NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    CONSTRAINT "Product_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Warehouse".users
(
    id integer NOT NULL DEFAULT nextval('"Warehouse"."Users_id_seq"'::regclass),
    name character varying(60) COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Users_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Warehouse".orders
(
    id integer NOT NULL DEFAULT nextval('"Warehouse"."Order_id_seq"'::regclass),
    status character varying COLLATE pg_catalog."default" NOT NULL,
    contents character varying COLLATE pg_catalog."default" NOT NULL,
    message character varying COLLATE pg_catalog."default",
    CONSTRAINT "Order_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Warehouse".routes
(
    id integer NOT NULL DEFAULT nextval('"Warehouse"."Routes_id_seq"'::regclass),
    route character varying COLLATE pg_catalog."default" NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT "Routes_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "Warehouse".routes
    ADD FOREIGN KEY (order_id)
    REFERENCES "Warehouse".orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;